# fly.toml app configuration file generated for cm3015midtermcoursework on 2025-01-06T03:00:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'cm3015midtermcoursework'
primary_region = 'syd'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[mounts]]
  source = "sqlite_data"
  destination = "/app/db"
