# Generated by Django 4.2.17 on 2025-01-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPhases',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('phase', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('daily_confirmed_cases', models.IntegerField(null=True)),
                ('false_positive_cases', models.IntegerField(null=True)),
                ('cumulative_cases', models.IntegerField(null=True)),
                ('daily_imported_cases', models.IntegerField(null=True)),
                ('daily_local_transmission_cases', models.IntegerField(null=True)),
                ('local_dorm_residence_cases', models.IntegerField(null=True)),
                ('local_non_dorm_residence_cases', models.IntegerField(null=True)),
                ('linked_community_cases', models.IntegerField(null=True)),
                ('unlinked_community_cases', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('daily_deaths', models.IntegerField(null=True)),
                ('cumulative_deaths', models.IntegerField(null=True)),
                ('non_covid_related_deaths', models.IntegerField(null=True)),
                ('covid_pos_deaths', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDischarges',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('total_hospital_discharges', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizedPatients',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('daily_discharged_patients', models.IntegerField(null=True)),
                ('cumulative_discharged_patients', models.IntegerField(null=True)),
                ('discharged_for_isolation', models.IntegerField(null=True)),
                ('still_hospitalized_patients', models.IntegerField(null=True)),
                ('ICU_patients', models.IntegerField(null=True)),
                ('general_wards_patients', models.IntegerField(null=True)),
                ('patients_in_isolation', models.IntegerField(null=True)),
                ('patients_requring_oxygen_supplementation_or_unstable', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsolationCases',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('total_completed_isolation_cases', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidData.covidphases')),
                ('cumulative_vaccine_doses', models.IntegerField(null=True)),
                ('cumulative_vaccinated_individuals', models.IntegerField(null=True)),
                ('cumulative_completed_vaccination_individuals', models.IntegerField(null=True)),
                ('percentage_of_population_who_completed_at_least_one_dose', models.FloatField(null=True)),
                ('percentage_of_population_who_completed_vaccination', models.FloatField(null=True)),
                ('sinovac_vaccine_doses', models.IntegerField(null=True)),
                ('cumulative_sinovac_vaccine_individuals', models.IntegerField(null=True)),
                ('doses_of_other_vaccines_recognised_by_WHO', models.IntegerField(null=True)),
                ('cumulative_individuals_using_other_vaccines_recognised_by_WHO', models.IntegerField(null=True)),
                ('individuals_who_took_booster_shots', models.IntegerField(null=True)),
                ('population_percentage_who_taken_booster_shots', models.FloatField(null=True)),
            ],
        ),
    ]
