# Generated by Django 4.2.17 on 2025-01-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name': 'Cases', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='covidphases',
            options={'verbose_name': 'CovidPhase', 'verbose_name_plural': 'CovidPhases'},
        ),
        migrations.AlterModelOptions(
            name='deaths',
            options={'verbose_name': 'Deaths', 'verbose_name_plural': 'Deaths'},
        ),
        migrations.AlterModelOptions(
            name='hospitaldischarges',
            options={'verbose_name': 'Hospital Discharges', 'verbose_name_plural': 'Hospital Discharges'},
        ),
        migrations.AlterModelOptions(
            name='hospitalizedpatients',
            options={'verbose_name': 'Hospitalized Patients', 'verbose_name_plural': 'Hospitalized Patients'},
        ),
        migrations.AlterModelOptions(
            name='isolationcases',
            options={'verbose_name': 'Isolation Cases', 'verbose_name_plural': 'Isolation Cases'},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vaccination', 'verbose_name_plural': 'Vaccination'},
        ),
    ]
